---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.disassembler.name }}-deployment
  labels:
    app: {{ .Values.disassembler.name }}
spec:
  replicas: {{ .Values.disassembler.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.disassembler.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.disassembler.name }}
    spec:
      containers:
      - name: {{ .Values.disassembler.name }}
        image: {{ .Values.disassembler.image }}
        imagePullPolicy: {{ .Values.disassembler.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.disassembler.containerPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.disassembler.containerPort }}
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.disassembler.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.disassembler.containerPort }}
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.disassembler.name }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.disassembler.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.disassembler.containerPort }}
