---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.fetchExecuteLoop.name }}-deployment
  labels:
    app: {{ .Values.fetchExecuteLoop.name }}
spec:
  replicas: {{ .Values.fetchExecuteLoop.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.fetchExecuteLoop.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fetchExecuteLoop.name }}
    spec:
      containers:
      - name: {{ .Values.fetchExecuteLoop.name }}
        image: {{ .Values.fetchExecuteLoop.image }}
        imagePullPolicy: {{ .Values.fetchExecuteLoop.imagePullPolicy }}
        env:
        - name: INTERRUPT_SERVICE_URL
          value: {{ tpl .Values.interruptServiceApi . }}
        - name: INITIALISE_CPU_SERVICE
          value: {{ tpl .Values.initaliseCpuApi . }}
        - name: READ_RANGE_API
          value: {{ tpl .Values.readRangeApi . }}
        - name: IN
          value: {{ tpl .Values.inApi . }}
        - name: OUT
          value: {{ tpl .Values.outApi . }}
        {{- range .Values.opcodes }}
        - name: {{ .name | upper }}
          value: http://opcode-{{ .name }}-service:{{ .containerPort }}/api/v1/execute
        {{- end }}
        ports:
        - containerPort: {{ .Values.fetchExecuteLoop.containerPort }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.fetchExecuteLoop.containerPort }}
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.fetchExecuteLoop.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /status
            port: {{ .Values.fetchExecuteLoop.containerPort }}
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.fetchExecuteLoop.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fetchExecuteLoop.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.fetchExecuteLoop.containerPort }}