---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.memoryBus.name }}-deployment
  labels:
    app: {{ .Values.memoryBus.name }}
spec:
  replicas: {{ .Values.memoryBus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.memoryBus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.memoryBus.name }}
    spec:
      containers:
      - name: {{ .Values.memoryBus.name }}
        image: {{ .Values.memoryBus.image }}
        imagePullPolicy: {{ .Values.memoryBus.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.memoryBus.containerPort }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.memoryBus.containerPort }}
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.memoryBus.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /status
            port: {{ .Values.memoryBus.containerPort }}
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.memoryBus.name }}-service
spec:
  selector:
    app: {{ .Values.memoryBus.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.memoryBus.containerPort }}
---