---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.memoryBus.name }}-deployment
  labels:
    app: {{ .Values.memoryBus.name }}
spec:
  replicas: {{ .Values.memoryBus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.memoryBus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.memoryBus.name }}
    spec:
      containers:
      - name: {{ .Values.memoryBus.name }}
        image: {{ .Values.memoryBus.image }}
        imagePullPolicy: {{ .Values.memoryBus.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.memoryBus.containerPort }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.memoryBus.containerPort }}
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.memoryBus.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /status
            port: {{ .Values.memoryBus.containerPort }}
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.memoryBus.name }}-service
spec:
  selector:
    app: {{ .Values.memoryBus.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.memoryBus.containerPort }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ .Values.memoryBus.name }}-service.{{ .Release.Namespace }}.svc.cluster.local
  namespace: {{ .Release.Namespace }}
spec:
  routes:
  - name: '/api/v1/readByte'
    condition:
      pathRegex: '/api/v1/readByte'
      method: GET
    isRetryable: true
    responseClasses:
      - condition:
          status:
            min: 500
            max: 599
        isFailure: true
  - name: '/api/v1/readRange'
    condition:
      pathRegex: '/api/v1/readRange'
      method: GET
    isRetryable: true
    responseClasses:
      - condition:
          status:
            min: 500
            max: 599
        isFailure: true
  - name: '/api/v1/writeByte'
    condition:
      pathRegex: '/api/v1/writeByte'
      method: POST
    isRetryable: true
    responseClasses:
      - condition:
          status:
            min: 500
            max: 599
        isFailure: true
  - name: '/api/v1/initialise'
    condition:
      pathRegex: '/api/v1/initialise'
      method: POST
    isRetryable: false
  retryBudget:
    retryRatio: 0.5
    minRetriesPerSecond: 10
    ttl: 5s