{{- range .Values.opcodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace }}
  name: opcode-{{ .name }}-deployment
  labels:
    app: opcode-{{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: opcode-{{ .name }}
  template:
    metadata:
      labels:
        app: opcode-{{ .name }}
    spec:
      containers:
      - name: opcode-{{ .name }}
        image: {{ .image }}
        imagePullPolicy: {{ .imagePullPolicy }}
        env:
        - name: READ_MEMORY_API
          value: {{ tpl $.Values.readByteApi $ }}
        - name: WRITE_MEMORY_API
          value: {{ tpl $.Values.writeByteApi $ }}
        ports:
        - containerPort: {{ .containerPort }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .containerPort }}
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /status
            port: {{ .containerPort }}
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: opcode-{{ .name }}-service
spec:
  selector:
    app: opcode-{{ .name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .containerPort }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: opcode-{{ .name }}-service.{{ $.Release.Namespace }}.svc.cluster.local
  namespace: {{ $.Release.Namespace }}
spec:
  routes:
  - name: '/api/v1/execute'
    condition:
      pathRegex: '/api/v1/execute'
      method: POST
    isRetryable: true
    responseClasses:
      - condition:
          status:
            min: 500
            max: 599
        isFailure: true
  retryBudget:
    retryRatio: 0.5
    minRetriesPerSecond: 10
    ttl: 5s
---
{{- end }}