---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.spaceInvadersUi.name }}-deployment
  labels:
    app: {{ .Values.spaceInvadersUi.name }}
spec:
  replicas: {{ .Values.spaceInvadersUi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.spaceInvadersUi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.spaceInvadersUi.name }}
    spec:
      containers:
      - name: {{ .Values.spaceInvadersUi.name }}
        image: {{ .Values.spaceInvadersUi.image }}
        imagePullPolicy: {{ .Values.spaceInvadersUi.imagePullPolicy }}
        env:
        - name: ApiEndpoints__ReadByteApi
          value: {{ tpl .Values.readByteApi . }}
        - name: ApiEndpoints__ReadWriteApi
          value: {{ tpl .Values.writeByteApi . }}
        - name: ApiEndpoints__ReadRangeApi
          value: {{ tpl .Values.readRangeApi . }}
        - name: ApiEndpoints__InitialiseMemoryApi
          value: {{ tpl .Values.initialiseMemoryApi . }}
        - name: ApiEndpoints__StartProgramApi
          value: {{ tpl .Values.startProgramApi . }}
        - name: ApiEndpoints__GetStatusApi
          value: {{ tpl .Values.programStateApi . }}
        ports:
        - containerPort: {{ .Values.spaceInvadersUi.containerPort }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.spaceInvadersUi.containerPort }}
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.spaceInvadersUi.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /status
            port: {{ .Values.spaceInvadersUi.containerPort }}
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.spaceInvadersUi.name }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.spaceInvadersUi.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.spaceInvadersUi.containerPort }}